-- ============================================================
-- 学伴小屋 · 建表脚本(PostgreSQL 16 + pgvector)
-- 配套:《数据库设计文档 v0.3》《数据库字段字典 v0.3》
--
-- 变更说明(v0.3):
--   1. t_order 状态机重构:引入"待收费"环节(信息费前置),新增 fee_* / fail_blame 字段
--   2. t_application 撤回=终态不可重投,新增部分唯一索引
--   3. 下架语义改为"可见性":编辑后审核通过才能恢复可见;t_demand 新增 review_* / edit_version
--   4. t_user 新增 mobile_hash(客服按手机号查找)
--   5. t_audit_log 新增 operator_id(操作人追溯)
--   6. t_dict 删除:字典复用 yudao system_dict_data(见 02-dict-data.sql 迁移脚本)
--
-- 执行前提:先由 yudao 初始化脚本建好框架表(system_/infra_ 前缀),
--          本脚本在同一数据库追加业务表(t_ 前缀),互不冲突。
-- 执行方式:psql -U <user> -d <db> -f 01-schema.sql
--
-- 通用约定:
--   · 状态/枚举一律 SMALLINT;纯二值 BOOLEAN;多值数组 JSONB(查询用 @>)
--   · created_at/updated_at 由应用层 autoFill 维护
--   · 业务表不物理删除,用状态字段控制(审核追溯需要)
--   · 手机号落库必 AES 加密,任何表不得存明文手机号
-- ============================================================

CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================================
-- 1. t_user 用户表
-- 业务用途:微信登录用户的账号主表,完整手机号唯一落点(AES 加密)
-- 关键规则:
--   · openid 为登录凭证,唯一
--   · mobile_hash 仅客服后台按手机号等值查找用(统一盐 SHA-256,不可逆)
--   · 身份规则:本表无身份字段;老师身份 = t_tutor_profile.cert_status=2,
--     家长身份 = t_parent_profile.publish_enabled=true,游客 = 两者皆无;三种身份可并存
--   · status=1 封禁为用户级处罚,两端全封
-- 关联:1 ── 0..1 t_tutor_profile;1 ── 0..1 t_parent_profile
-- ============================================================
CREATE TABLE t_user (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 主键,自增
    openid           VARCHAR(64)  NOT NULL,                              -- 微信 openid,登录凭证(唯一)
    unionid          VARCHAR(64),                                        -- 微信 unionid(预留,暂无公众号,可空)
    nickname         VARCHAR(64),                                        -- 微信昵称
    avatar_url       VARCHAR(512),                                       -- 微信头像 URL
    mobile_encrypted VARCHAR(256),                                       -- AES 加密手机号(注册/首次发布时必填;解密仅后台接口有权)
    mobile_hash      VARCHAR(64),                                        -- 手机号统一盐 SHA-256 哈希(盐在环境变量),仅客服后台等值查找,不可逆
    last_city        VARCHAR(32),                                        -- 最后定位城市(仅用于首页默认城市)
    status           SMALLINT     NOT NULL DEFAULT 0,                    -- 0 正常 / 1 封禁(用户级,两端全封)
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,    -- 创建时间
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP     -- 更新时间
);
CREATE UNIQUE INDEX uk_t_user_openid      ON t_user (openid);        -- 登录凭证唯一
CREATE INDEX        idx_t_user_mobile_hash ON t_user (mobile_hash);  -- 客服按手机号哈希查找

COMMENT ON TABLE  t_user               IS '用户表(微信登录,完整手机号唯一落点,AES 加密)';
COMMENT ON COLUMN t_user.id               IS '主键,自增';
COMMENT ON COLUMN t_user.openid           IS '微信 openid,登录凭证,唯一';
COMMENT ON COLUMN t_user.unionid          IS '微信 unionid,预留(暂无公众号)';
COMMENT ON COLUMN t_user.nickname         IS '微信昵称';
COMMENT ON COLUMN t_user.avatar_url       IS '微信头像 URL';
COMMENT ON COLUMN t_user.mobile_encrypted IS 'AES 加密手机号,解密仅后台接口有权';
COMMENT ON COLUMN t_user.mobile_hash      IS '手机号统一盐 SHA-256 哈希,仅用于客服后台按手机号等值查找,不可逆';
COMMENT ON COLUMN t_user.last_city        IS '最后定位城市(仅用于首页默认城市)';
COMMENT ON COLUMN t_user.status           IS '0 正常 / 1 封禁(用户级处罚,两端全封)';
COMMENT ON COLUMN t_user.created_at       IS '创建时间';
COMMENT ON COLUMN t_user.updated_at       IS '更新时间';

-- ============================================================
-- 2. t_tutor_profile 老师身份表(每老师一行)
-- 业务用途:老师身份的认证状态、反悔与举报计数、强制下线
-- 关键规则:
--   · cert_status=2(已通过)才拥有老师身份:可看需求广场/投递/简历可见
--   · 认证材料:学生证照片 + 学信网截图(个人照片已取消,头像选填在简历表)
--   · 反悔次数满 3 → 自动 blacklist=true(禁投递、简历强制隐藏)
--   · 身份级处罚不连坐:blacklist 不影响该用户的家长身份
--   · 申诉恢复:blacklist=false + 计数清零,历史保留在 t_break_promise_log
-- 关联:t_user 1 ── 0..1;t_tutor_resume 1 ── 1
-- ============================================================
CREATE TABLE t_tutor_profile (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 主键,自增
    user_id              BIGINT       NOT NULL,                          -- 关联 t_user.id(唯一,一人一行)
    cert_status          SMALLINT     NOT NULL DEFAULT 0,                -- 认证状态:0 未提交 / 1 待审核 / 2 已通过 / 3 已拒绝
    cert_student_card    VARCHAR(512),                                   -- 学生证照片 URL
    cert_xuexin          VARCHAR(512),                                   -- 学信网截图 URL
    cert_reject_reason   VARCHAR(255),                                   -- 拒绝原因(老师可见,可修改材料后重提)
    cert_audit_at        TIMESTAMP,                                      -- 最近一次认证审核时间
    break_promise_count  INT          NOT NULL DEFAULT 0,                -- 反悔次数(被选中后拒绝),满 3 触发 blacklist=true
    report_count         INT          NOT NULL DEFAULT 0,                -- 举报核实次数(排序隐藏权重;核实成立强制隐藏简历)
    blacklist            BOOLEAN      NOT NULL DEFAULT false,            -- 强制下线开关:禁投递、简历强制隐藏
    blacklist_reason     VARCHAR(255),                                   -- 下线原因
    appeal_status        SMALLINT     NOT NULL DEFAULT 0,                -- 申诉状态:0 无申诉 / 1 申诉中 / 2 已恢复
    created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 创建时间
    updated_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP  -- 更新时间
);
CREATE UNIQUE INDEX uk_t_tutor_profile_user ON t_tutor_profile (user_id);  -- 一人一身份行

COMMENT ON TABLE  t_tutor_profile              IS '老师身份表(认证状态+反悔+举报+下线);老师身份拥有 = cert_status=2';
COMMENT ON COLUMN t_tutor_profile.user_id        IS '关联 t_user.id,唯一(一人一行)';
COMMENT ON COLUMN t_tutor_profile.cert_status    IS '认证状态:0 未提交 / 1 待审核 / 2 已通过 / 3 已拒绝;通过前不可看需求广场/投递/简历可见';
COMMENT ON COLUMN t_tutor_profile.cert_student_card IS '学生证照片 URL';
COMMENT ON COLUMN t_tutor_profile.cert_xuexin    IS '学信网截图 URL';
COMMENT ON COLUMN t_tutor_profile.cert_reject_reason IS '拒绝原因(老师可见,可修改材料后重提)';
COMMENT ON COLUMN t_tutor_profile.cert_audit_at  IS '最近一次认证审核时间';
COMMENT ON COLUMN t_tutor_profile.break_promise_count IS '反悔次数(被选中后拒绝),满 3 触发 blacklist=true';
COMMENT ON COLUMN t_tutor_profile.report_count   IS '举报核实次数(排序隐藏权重;核实成立强制隐藏简历)';
COMMENT ON COLUMN t_tutor_profile.blacklist      IS '强制下线:禁投递、简历强制隐藏;申诉恢复后计数清零,历史在 t_break_promise_log';
COMMENT ON COLUMN t_tutor_profile.blacklist_reason IS '下线原因';
COMMENT ON COLUMN t_tutor_profile.appeal_status  IS '0 无申诉 / 1 申诉中 / 2 已恢复';
COMMENT ON COLUMN t_tutor_profile.created_at     IS '创建时间';
COMMENT ON COLUMN t_tutor_profile.updated_at     IS '更新时间';

-- ============================================================
-- 3. t_tutor_resume 简历表(一人一行,持续更新)
-- 业务用途:老师的家教简历,简历广场数据源
-- 关键规则:
--   · 实际可见 = visible AND review_status=1 AND profile.blacklist=false AND profile.cert_status=2
--   · 敏感字段(学校/学历/擅长学科)编辑 → review_status 回 0 且强制 visible=false,审核通过自动恢复可见
--   · 非敏感字段编辑不重审(走敏感词检测),可见性不受影响
--   · 隐藏期间存量申请在家长端查询时排除;已生成订单不受影响
--   · embedding 向量列先建不填充,二期批跑回填后启用语义检索
--   · 禁止字段:简历任何位置无微信号(个人介绍中出现的微信号由客服审核时删除)
-- 关联:t_tutor_profile 1 ── 1
-- ============================================================
CREATE TABLE t_tutor_resume (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 主键,自增
    user_id       BIGINT       NOT NULL,                               -- 关联 t_user.id(唯一,一人一简历)
    name          VARCHAR(32)  NOT NULL,                               -- 姓名
    avatar_url    VARCHAR(512),                                        -- 头像(选填,微信头像能力 chooseAvatar 一键带入)
    gender        SMALLINT     NOT NULL,                               -- 性别:1 男 / 2 女
    school        VARCHAR(64)  NOT NULL,                               -- 学校(敏感字段,编辑触发重审)
    education     VARCHAR(32)  NOT NULL,                               -- 学历枚举(字典 education:college/bachelor/p211/p985/master/doctor)
    subjects      JSONB        NOT NULL DEFAULT '[]'::jsonb,           -- 擅长学科数组(字典 subject,敏感字段),如 ["math","physics"]
    teach_grades  JSONB        NOT NULL DEFAULT '[]'::jsonb,           -- 可授课年级数组(字典 grade),如 ["junior1","junior2"]
    experience    TEXT,                                                -- 家教经验(非敏感)
    teach_time    JSONB,                                               -- 可授课时间结构,如 [{"day":"周末","slots":["上午","下午"]}]
    teach_areas   JSONB        NOT NULL DEFAULT '[]'::jsonb,           -- 可授课区域数组,如 ["海淀区","朝阳区"]
    hourly_min    DECIMAL(6,1),                                        -- 期望时薪下限(元/小时)
    hourly_max    DECIMAL(6,1),                                        -- 期望时薪上限(元/小时)
    intro         TEXT,                                                -- 个人介绍(非敏感,人工审核删微信号)
    embedding     vector(1024),                                        -- 语义向量(先建列不填充,二期 embedding 批跑回填)
    visible       BOOLEAN      NOT NULL DEFAULT false,                 -- 可见性开关:true 可见;审核中/被拒/强制下线时系统强制 false(仅控制他人能否看到/申请,不涉及内容编辑)
    review_status SMALLINT     NOT NULL DEFAULT 0,                     -- 审核状态:0 待审核 / 1 通过 / 2 拒绝(敏感字段编辑→回 0 且强制隐藏)
    review_reason VARCHAR(255),                                        -- 审核意见
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,     -- 创建时间
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP      -- 更新时间
);
CREATE UNIQUE INDEX uk_t_tutor_resume_user    ON t_tutor_resume (user_id);               -- 一人一简历
CREATE INDEX        idx_t_tutor_resume_shelf  ON t_tutor_resume (review_status, visible); -- 简历广场按审核+可见过滤
CREATE INDEX        idx_t_tutor_resume_edu    ON t_tutor_resume (education);             -- 按学历筛选
CREATE INDEX        gin_t_tutor_resume_subjects ON t_tutor_resume USING gin (subjects);  -- 按学科筛选(JSONB @>)
CREATE INDEX        gin_t_tutor_resume_areas  ON t_tutor_resume USING gin (teach_areas); -- 按区域筛选(JSONB @>)
-- 语义检索索引:数据积累、embedding 回填后启用
-- CREATE INDEX hnsw_t_tutor_resume_embedding ON t_tutor_resume USING hnsw (embedding vector_cosine_ops);

COMMENT ON TABLE  t_tutor_resume              IS '简历表(一人一简历,持续更新);简历广场数据源';
COMMENT ON COLUMN t_tutor_resume.user_id        IS '关联 t_user.id,唯一(一人一简历)';
COMMENT ON COLUMN t_tutor_resume.name           IS '姓名';
COMMENT ON COLUMN t_tutor_resume.avatar_url     IS '头像(选填,微信头像能力 chooseAvatar 实现)';
COMMENT ON COLUMN t_tutor_resume.gender         IS '1 男 / 2 女';
COMMENT ON COLUMN t_tutor_resume.school         IS '学校(敏感字段,编辑触发重审)';
COMMENT ON COLUMN t_tutor_resume.education      IS '学历枚举(字典 education)';
COMMENT ON COLUMN t_tutor_resume.subjects       IS '擅长学科数组(字典 subject,敏感字段,编辑触发重审)';
COMMENT ON COLUMN t_tutor_resume.teach_grades   IS '可授课年级数组(字典 grade)';
COMMENT ON COLUMN t_tutor_resume.experience     IS '家教经验(非敏感)';
COMMENT ON COLUMN t_tutor_resume.teach_time     IS '可授课时间结构,如 [{"day":"周末","slots":["上午","下午"]}]';
COMMENT ON COLUMN t_tutor_resume.teach_areas    IS '可授课区域数组';
COMMENT ON COLUMN t_tutor_resume.hourly_min     IS '期望时薪下限(元/小时)';
COMMENT ON COLUMN t_tutor_resume.hourly_max     IS '期望时薪上限(元/小时)';
COMMENT ON COLUMN t_tutor_resume.intro          IS '个人介绍(非敏感,人工审核删微信号)';
COMMENT ON COLUMN t_tutor_resume.embedding      IS '语义向量(1024 维),由 intro+subjects+experience 经 embedding API 生成,二期批跑回填';
COMMENT ON COLUMN t_tutor_resume.visible        IS '可见性开关:true 可见 / false 隐藏,仅控制他人能否看到/申请,不涉及内容编辑;隐藏期间存量申请在家长端查询时排除';
COMMENT ON COLUMN t_tutor_resume.review_status  IS '审核状态:0 待审核 / 1 通过 / 2 拒绝;敏感字段编辑 → 回 0 且强制隐藏,审核通过自动恢复可见';
COMMENT ON COLUMN t_tutor_resume.review_reason  IS '审核意见';
COMMENT ON COLUMN t_tutor_resume.created_at     IS '创建时间';
COMMENT ON COLUMN t_tutor_resume.updated_at     IS '更新时间';

-- ============================================================
-- 4. t_parent_profile 家长身份表(每家长一行)
-- 业务用途:家长身份的发布需求权(人工审核开通)
-- 关键规则:
--   · publish_enabled=true 才拥有家长身份:可发布需求
--   · 审核流程:家长先加客服微信(wechat_confirmed)→ 客服朋友圈判断 → 人工开通
--   · 举报核实成立 → 强制下架其全部需求(不连坐其老师身份)
-- 关联:t_user 1 ── 0..1
-- ============================================================
CREATE TABLE t_parent_profile (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 主键,自增
    user_id          BIGINT       NOT NULL,                          -- 关联 t_user.id(唯一,一人一行)
    publish_enabled  BOOLEAN      NOT NULL DEFAULT false,            -- 发布需求权(客服加微信+朋友圈判断后人工开通)
    wechat_confirmed BOOLEAN      NOT NULL DEFAULT false,            -- 是否已确认加客服微信
    report_count     INT          NOT NULL DEFAULT 0,                -- 举报核实次数(核实成立强制下架其全部需求)
    audit_note       VARCHAR(255),                                   -- 客服审核备注(对用户不可见)
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 创建时间
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP  -- 更新时间
);
CREATE UNIQUE INDEX uk_t_parent_profile_user ON t_parent_profile (user_id);  -- 一人一身份行

COMMENT ON TABLE  t_parent_profile               IS '家长身份表(发布需求权由客服人工开通);家长身份拥有 = publish_enabled=true';
COMMENT ON COLUMN t_parent_profile.user_id         IS '关联 t_user.id,唯一(一人一行)';
COMMENT ON COLUMN t_parent_profile.publish_enabled IS '发布需求权:加客服微信+朋友圈判断后人工开通';
COMMENT ON COLUMN t_parent_profile.wechat_confirmed IS '是否已确认加客服微信';
COMMENT ON COLUMN t_parent_profile.report_count    IS '举报核实次数(核实成立强制下架其全部需求,不连坐老师身份)';
COMMENT ON COLUMN t_parent_profile.audit_note      IS '客服审核备注(对用户不可见)';
COMMENT ON COLUMN t_parent_profile.created_at      IS '创建时间';
COMMENT ON COLUMN t_parent_profile.updated_at      IS '更新时间';

-- ============================================================
-- 5. t_demand 需求表(家长可发多个)
-- 业务用途:家长发布的家教需求单,需求广场数据源
-- 关键规则:
--   · status 状态机:0 接收申请中(可见可申请)/ 1 已选定老师(不接受新申请)/ 2 已关闭(完成/失败/超时/家长手动下架/举报核实/家长放弃);2→0 可重开
--   · 可见性:status=0 且 review_status=1 才对外可见可申请
--   · 敏感字段(科目/年级/地址/时薪)编辑 → review_status 回 0 且强制不可见,审核通过恢复
--   · 非敏感字段编辑走敏感词检测,不重审
--   · 重开规则:对比 edit_version 判定"编辑过"——编辑过 → 原申请置 5 失效;未编辑 → 原申请保留
--   · 地址前台脱敏(仅到区);详细地址与坐标仅客服后台可见
--   · 家长活跃需求上限:同时"接收申请中"最多 3 个(应用层控制)
-- 关联:t_user(parent_user_id);t_application 1 ── 0..n;t_order 1 ── 0..n
-- ============================================================
CREATE TABLE t_demand (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 主键,自增
    parent_user_id   BIGINT       NOT NULL,                          -- 发布家长(关联 t_user.id)
    subjects         JSONB        NOT NULL DEFAULT '[]'::jsonb,      -- 授课科目数组(字典 subject,敏感字段)
    grade            VARCHAR(32)  NOT NULL,                          -- 学段枚举(字典 grade,敏感字段)
    hourly_min       DECIMAL(6,1),                                   -- 期望时薪下限(元/小时,敏感字段)
    hourly_max       DECIMAL(6,1),                                   -- 期望时薪上限(元/小时,敏感字段)
    tutor_gender_req SMALLINT     NOT NULL DEFAULT 0,                -- 性别要求:0 不限 / 1 男 / 2 女
    tutor_edu_req    VARCHAR(32),                                    -- 学历要求枚举(字典 education,空=不限)
    city             VARCHAR(32)  NOT NULL,                          -- 城市(敏感字段)
    district         VARCHAR(32)  NOT NULL,                          -- 区(前台展示仅到区)
    address_detail   VARCHAR(255) NOT NULL,                          -- 详细地址到小区/街道(前台脱敏不展示,敏感字段)
    address_lat      DECIMAL(10,6),                                  -- 地址纬度(geocoder 转坐标,前台不可见,仅距离计算用)
    address_lng      DECIMAL(10,6),                                  -- 地址经度(同上)
    teach_time_req   JSONB,                                          -- 授课时间要求(结构化,同简历 teach_time 格式)
    student_info     TEXT,                                           -- 学生情况(非敏感)
    remark           TEXT,                                           -- 备注/其他要求(非敏感,自由文本,不入筛选)
    status           SMALLINT     NOT NULL DEFAULT 0,                -- 状态:0 接收申请中 / 1 已选定老师 / 2 已关闭
    review_status    SMALLINT     NOT NULL DEFAULT 0,                -- 审核状态:0 待审核 / 1 通过 / 2 拒绝(敏感字段编辑→回 0 且强制不可见)
    review_reason    VARCHAR(255),                                   -- 审核意见
    edit_version     INT          NOT NULL DEFAULT 0,                -- 编辑版本号(每次保存内容 +1;重开时对比判定"编辑过")
    expire_at        TIMESTAMP,                                      -- 超时下架时间(发布后一周无人接单 → 定时任务提醒管理员,持续无人接自动下架)
    closed_reason    VARCHAR(64),                                    -- 关闭原因:已完成/试课失败/超时/家长手动下架/举报核实/家长放弃
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 创建时间
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP  -- 更新时间
);
CREATE INDEX idx_t_demand_shelf     ON t_demand (status, city);              -- 需求广场按状态+城市过滤
CREATE INDEX idx_t_demand_parent    ON t_demand (parent_user_id);            -- 我的需求列表
CREATE INDEX gin_t_demand_subjects  ON t_demand USING gin (subjects);        -- 按科目筛选(JSONB @>)

COMMENT ON TABLE  t_demand                IS '需求表(家长可发多个;编辑后审核通过才能恢复可见)';
COMMENT ON COLUMN t_demand.parent_user_id IS '发布家长(关联 t_user.id)';
COMMENT ON COLUMN t_demand.subjects       IS '授课科目数组(字典 subject,敏感字段)';
COMMENT ON COLUMN t_demand.grade          IS '学段枚举(字典 grade,敏感字段)';
COMMENT ON COLUMN t_demand.hourly_min     IS '期望时薪下限(元/小时,敏感字段)';
COMMENT ON COLUMN t_demand.hourly_max     IS '期望时薪上限(元/小时,敏感字段)';
COMMENT ON COLUMN t_demand.tutor_gender_req IS '性别要求:0 不限 / 1 男 / 2 女';
COMMENT ON COLUMN t_demand.tutor_edu_req  IS '学历要求枚举(字典 education,空=不限)';
COMMENT ON COLUMN t_demand.city           IS '城市(敏感字段)';
COMMENT ON COLUMN t_demand.district       IS '区(前台展示仅到区)';
COMMENT ON COLUMN t_demand.address_detail IS '详细地址到小区/街道(前台脱敏不展示,敏感字段)';
COMMENT ON COLUMN t_demand.address_lat    IS '地址纬度(geocoder 转坐标,前台不可见,仅距离计算用)';
COMMENT ON COLUMN t_demand.address_lng    IS '地址经度(同上)';
COMMENT ON COLUMN t_demand.teach_time_req IS '授课时间要求(结构化,同简历 teach_time 格式)';
COMMENT ON COLUMN t_demand.student_info   IS '学生情况(非敏感)';
COMMENT ON COLUMN t_demand.remark         IS '备注/其他要求(非敏感,自由文本,不入筛选)';
COMMENT ON COLUMN t_demand.status         IS '状态:0 接收申请中(可见可申请)/ 1 已选定老师 / 2 已关闭(完成/失败/超时/家长手动下架/举报核实/家长放弃)';
COMMENT ON COLUMN t_demand.review_status  IS '审核状态:0 待审核 / 1 通过 / 2 拒绝;敏感字段编辑 → 回 0 且强制不可见,审核通过恢复';
COMMENT ON COLUMN t_demand.review_reason  IS '审核意见';
COMMENT ON COLUMN t_demand.edit_version   IS '编辑版本号(每次保存内容 +1;重开时对比快照值判定"编辑过"→ 编辑过则原申请置 5 失效)';
COMMENT ON COLUMN t_demand.expire_at      IS '超时下架时间(一周无人接单 → 后台提示管理员 → 持续无人接自动下架)';
COMMENT ON COLUMN t_demand.closed_reason  IS '关闭原因:已完成/试课失败/超时/家长手动下架/举报核实/家长放弃';
COMMENT ON COLUMN t_demand.created_at     IS '创建时间';
COMMENT ON COLUMN t_demand.updated_at     IS '更新时间';

-- ============================================================
-- 6. t_application 申请表(老师投递记录)
-- 业务用途:老师向需求单投递的申请记录,家长选老师的数据源
-- 关键规则(状态机):
--   · 0 申请中 → 1 被选中(家长选中,同时生成订单)
--   · 0 → 2 已撤回(家长未选前可撤回,终态,不可重投该需求)
--   · 1 → 3 已排除(老师反悔,家长不可再选他)
--   · 0 → 5 已失效(需求编辑后重开,原申请清空;失效行可重新投递新行)
--   · 4 已试课未通过 → 1 可再选(同行走状态流转,不产生新行)
--   · 部分唯一索引:同一老师对同一需求仅一行活跃申请(除 5 已失效外)
--   · 简历隐藏期间,其 status=0 的申请在家长端查询时排除(展示层规则,状态不变)
-- 关联:t_demand 1 ── 0..n;t_order 1 ── 0..n(试课失败后再选产生新订单)
-- ============================================================
CREATE TABLE t_application (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 主键,自增
    demand_id     BIGINT    NOT NULL,                                  -- 目标需求(关联 t_demand.id)
    tutor_user_id BIGINT    NOT NULL,                                  -- 投递老师(关联 t_user.id)
    status        SMALLINT  NOT NULL DEFAULT 0,                        -- 状态:0 申请中 / 1 被选中 / 2 已撤回(终态) / 3 已排除(反悔) / 4 已试课未通过(可再选) / 5 已失效
    apply_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,        -- 投递时间
    updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP         -- 更新时间
);
CREATE INDEX idx_t_application_demand      ON t_application (demand_id, status);     -- 家长端申请列表
CREATE INDEX idx_t_application_tutor       ON t_application (tutor_user_id, status); -- 老师端我的申请
-- 同一老师对同一需求仅一行(撤回=终态不可重投;试课失败可再选走同行走状态流转;仅"5 已失效"不占位,允许重新投递)
CREATE UNIQUE INDEX uk_t_application_demand_tutor ON t_application (demand_id, tutor_user_id) WHERE status IN (0, 1, 2, 3, 4);

COMMENT ON TABLE  t_application              IS '老师投递记录(申请);家长选老师的数据源';
COMMENT ON COLUMN t_application.demand_id      IS '目标需求(关联 t_demand.id)';
COMMENT ON COLUMN t_application.tutor_user_id  IS '投递老师(关联 t_user.id)';
COMMENT ON COLUMN t_application.status         IS '0 申请中 / 1 被选中 / 2 已撤回(终态,不可重投该需求)/ 3 已排除(反悔)/ 4 已试课未通过(可再选)/ 5 已失效(需求编辑重上架清空,可重新投递)';
COMMENT ON COLUMN t_application.apply_at       IS '投递时间';
COMMENT ON COLUMN t_application.updated_at     IS '更新时间';

-- ============================================================
-- 7. t_order 订单表
-- 业务用途:订单全生命周期,信息费前置收费的载体,动态墙数据源
-- 关键规则(状态机,信息费前置):
--   0 待确认(家长已选,等老师确认;超 12 小时每日 8:00 定时任务提醒管理员催办,不自动取消)
--     ├─老师确认 → 1 待收费(双方加客服微信)
--     └─老师反悔 → 5 已取消(需求回退 0,application 置 3,break_promise_count+1)
--   1 待收费 ──客服收费+发放联系方式──→ 2 试课中(fee_status=1)
--   2 试课中 ──客服标记──→ 3 已完成(需求关闭)/ 4 试课失败(先退费,fee_status=2 强制)
--   任意收费前 ──家长放弃(管理端取消)──→ 5 已取消(需求关闭)
--   收费后家长放弃 → 管理端取消 + 退费 → 5 已取消(fee_status=2)
--   · 试课失败必填 fail_blame(1 老师问题 / 2 家长问题)+ fail_reason,审计追溯
--   · 试课失败后续:家长还要老师 → 需求回退 0;家长不要了 → 需求关闭 2
--   · 动态墙投影:status IN (2,3) 且严格脱敏(区/学段/科目/状态/时间)
-- 关联:t_demand / t_application / t_evaluation 1 ── 0..2
-- ============================================================
CREATE TABLE t_order (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 主键,自增
    demand_id          BIGINT    NOT NULL,                              -- 关联需求(关联 t_demand.id)
    application_id     BIGINT    NOT NULL,                              -- 来源申请(关联 t_application.id)
    parent_user_id     BIGINT    NOT NULL,                              -- 家长(关联 t_user.id)
    tutor_user_id      BIGINT    NOT NULL,                              -- 老师(关联 t_user.id)
    status             SMALLINT  NOT NULL DEFAULT 0,                    -- 状态:0 待确认 / 1 待收费 / 2 试课中 / 3 已完成 / 4 试课失败 / 5 已取消
    fee_status         SMALLINT  NOT NULL DEFAULT 0,                    -- 信息费状态:0 未收 / 1 已收 / 2 已退(状态 4 强制为 2)
    fee_collected_at   TIMESTAMP,                                       -- 收费时间(→试课中,线下微信收取 99 元)
    fee_refunded_at    TIMESTAMP,                                       -- 退费时间(试课失败/收费后取消)
    fail_blame         SMALLINT,                                        -- 失败责任方:1 老师问题 / 2 家长问题(客服沟通后填写,审计追溯用)
    fail_reason        VARCHAR(255),                                    -- 试课失败原因(客服填)
    cancel_reason      VARCHAR(255),                                    -- 取消原因(老师反悔/家长放弃,客服填)
    tutor_confirmed_at TIMESTAMP,                                       -- 老师确认时间(→待收费)
    finished_at        TIMESTAMP,                                       -- 完成时间(客服标记)
    created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,    -- 订单生成时间(家长选中)
    updated_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP     -- 更新时间
);
CREATE INDEX idx_t_order_tutor  ON t_order (tutor_user_id, status);     -- 老师端我的订单
CREATE INDEX idx_t_order_parent ON t_order (parent_user_id, status);    -- 家长端我的订单
CREATE INDEX idx_t_order_feed   ON t_order (status, updated_at);        -- 动态墙投影(status IN 2,3 按时间倒序)

COMMENT ON TABLE  t_order            IS '订单表(信息费前置;动态墙数据源,只读投影)';
COMMENT ON COLUMN t_order.demand_id        IS '关联需求(关联 t_demand.id)';
COMMENT ON COLUMN t_order.application_id   IS '来源申请(关联 t_application.id)';
COMMENT ON COLUMN t_order.parent_user_id   IS '家长(关联 t_user.id)';
COMMENT ON COLUMN t_order.tutor_user_id    IS '老师(关联 t_user.id)';
COMMENT ON COLUMN t_order.status           IS '状态:0 待确认(家长已选,等老师确认)/ 1 待收费(老师已确认,双方加客服微信)/ 2 试课中(已收费已发联系方式)/ 3 已完成 / 4 试课失败(已退费)/ 5 已取消';
COMMENT ON COLUMN t_order.fee_status       IS '信息费状态:0 未收 / 1 已收 / 2 已退;状态 4 必须为 2(退费后才能标记失败)';
COMMENT ON COLUMN t_order.fee_collected_at IS '收费时间(→试课中,线下微信收取,统一 99 元)';
COMMENT ON COLUMN t_order.fee_refunded_at  IS '退费时间(试课失败/收费后取消)';
COMMENT ON COLUMN t_order.fail_blame       IS '失败责任方:1 老师问题 / 2 家长问题(客服与家长沟通后填写,审计追溯用)';
COMMENT ON COLUMN t_order.fail_reason      IS '试课失败原因(客服填)';
COMMENT ON COLUMN t_order.cancel_reason    IS '取消原因(老师反悔/家长放弃,客服填)';
COMMENT ON COLUMN t_order.tutor_confirmed_at IS '老师确认时间(→待收费)';
COMMENT ON COLUMN t_order.finished_at      IS '完成时间(客服标记)';
COMMENT ON COLUMN t_order.created_at       IS '订单生成时间(家长选中);超 12 小时未确认 → 每日 8:00 定时任务提醒管理员催办,不自动取消';
COMMENT ON COLUMN t_order.updated_at       IS '更新时间';

-- ============================================================
-- 8. t_evaluation 评价表(挂人,不挂简历/需求)
-- 业务用途:订单完成后双方互评,老师公开口碑,家长评价仅客服可见
-- 关键规则:
--   · 评价对象是人(user 维度,to_user_id),换简历/发新需求历史评价跟着人走
--   · 评价资格:订单进入试课中(status=2)后开放,终态 3/4 均保留资格;每订单每方向一条(UNIQUE)
--   · 家长评老师(direction=1):公开,老师详情页聚合平均分
--   · 老师评家长(direction=2):仅客服后台可见(API 层控制,防报复差评)
--   · 差评(≤2 星)先客服审核:0 待审核 → 1 公开生效 / 2 已隐藏;被评人有申诉渠道
-- 关联:t_order 1 ── 0..2(每方向至多一条)
-- ============================================================
CREATE TABLE t_evaluation (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 主键,自增
    order_id     BIGINT       NOT NULL,                               -- 关联订单(关联 t_order.id)
    direction    SMALLINT     NOT NULL,                               -- 方向:1 家长评老师(公开)/ 2 老师评家长(仅后台可见)
    from_user_id BIGINT       NOT NULL,                               -- 评价人(关联 t_user.id)
    to_user_id   BIGINT       NOT NULL,                               -- 被评人(关联 t_user.id,user 维度,跟人走)
    stars        SMALLINT     NOT NULL,                               -- 星级 1-5(CHECK 约束)
    tags         JSONB,                                               -- 标签数组(字典 eval_tag 的 value),如 ["teaching","punctual"]
    content      VARCHAR(500),                                        -- 文字评价
    status       SMALLINT     NOT NULL DEFAULT 0,                     -- 状态:0 待客服审核(≤2 星差评)/ 1 公开生效 / 2 已隐藏
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,     -- 评价时间
    CONSTRAINT chk_t_evaluation_stars CHECK (stars BETWEEN 1 AND 5)
);
CREATE UNIQUE INDEX uk_t_evaluation_order_dir ON t_evaluation (order_id, direction); -- 每订单每方向至多一条
CREATE INDEX        idx_t_evaluation_to_user  ON t_evaluation (to_user_id, status);  -- 老师详情页聚合平均分

COMMENT ON TABLE  t_evaluation              IS '评价表(挂人不挂简历/需求;订单进入试课中后开放互评)';
COMMENT ON COLUMN t_evaluation.order_id       IS '关联订单(关联 t_order.id)';
COMMENT ON COLUMN t_evaluation.direction      IS '方向:1 家长评老师(公开)/ 2 老师评家长(仅后台可见)';
COMMENT ON COLUMN t_evaluation.from_user_id   IS '评价人(关联 t_user.id)';
COMMENT ON COLUMN t_evaluation.to_user_id     IS '被评人(关联 t_user.id,user 维度,跟人走)';
COMMENT ON COLUMN t_evaluation.stars          IS '星级 1-5(CHECK 约束)';
COMMENT ON COLUMN t_evaluation.tags           IS '标签数组(字典 eval_tag 的 value)';
COMMENT ON COLUMN t_evaluation.content        IS '文字评价';
COMMENT ON COLUMN t_evaluation.status         IS '状态:0 待客服审核(≤2 星差评)/ 1 公开生效 / 2 已隐藏';
COMMENT ON COLUMN t_evaluation.created_at     IS '评价时间';

-- ============================================================
-- 9. t_report 举报表
-- 业务用途:双向举报(家长举报老师 / 老师举报家长)
-- 关键规则:
--   · 举报后相关订单由客服工作台人工跟进冻结(不加订单状态字段)
--   · 核实成立(status=1)→ 目标对应 profile.report_count+1 + 强制下架其简历/需求 + 站内信通知
--   · 驳回(status=2)则无事;申诉恢复时计数不减,由客服在 t_audit_log 记录
-- 关联:t_user(举报人/被举报人);t_order(可空)
-- ============================================================
CREATE TABLE t_report (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 主键,自增
    reporter_user_id BIGINT       NOT NULL,                          -- 举报人(关联 t_user.id)
    target_user_id   BIGINT       NOT NULL,                          -- 被举报人(关联 t_user.id)
    target_role      SMALLINT     NOT NULL,                          -- 被举报身份:1 老师 / 2 家长
    reason_type      SMALLINT     NOT NULL,                          -- 举报原因:1 虚假信息 / 2 骚扰 / 3 人身安全 / 4 其他
    detail           VARCHAR(500),                                   -- 举报说明
    related_order_id BIGINT,                                         -- 关联订单(可空,关联 t_order.id)
    status           SMALLINT     NOT NULL DEFAULT 0,                -- 状态:0 待处理 / 1 已核实(成立)/ 2 已驳回
    handle_note      VARCHAR(255),                                   -- 客服处理备注
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 举报时间
    handled_at       TIMESTAMP                                        -- 处理时间
);
CREATE INDEX idx_t_report_target   ON t_report (target_user_id, status);   -- 按被举报人查询
CREATE INDEX idx_t_report_reporter ON t_report (reporter_user_id);         -- 按举报人查询

COMMENT ON TABLE  t_report              IS '举报表(双向;核实成立 → 目标 report_count+1 + 强制下架其简历/需求)';
COMMENT ON COLUMN t_report.reporter_user_id IS '举报人(关联 t_user.id)';
COMMENT ON COLUMN t_report.target_user_id   IS '被举报人(关联 t_user.id)';
COMMENT ON COLUMN t_report.target_role      IS '被举报身份:1 老师 / 2 家长';
COMMENT ON COLUMN t_report.reason_type      IS '举报原因:1 虚假信息 / 2 骚扰 / 3 人身安全 / 4 其他';
COMMENT ON COLUMN t_report.detail           IS '举报说明';
COMMENT ON COLUMN t_report.related_order_id IS '关联订单(可空,关联 t_order.id)';
COMMENT ON COLUMN t_report.status           IS '状态:0 待处理 / 1 已核实(成立)/ 2 已驳回';
COMMENT ON COLUMN t_report.handle_note      IS '客服处理备注';
COMMENT ON COLUMN t_report.created_at       IS '举报时间';
COMMENT ON COLUMN t_report.handled_at       IS '处理时间';

-- ============================================================
-- 10. t_break_promise_log 反悔历史表(仅后台)
-- 业务用途:老师反悔的历史留痕,申诉审计依据
-- 关键规则:申诉恢复后计数清零(t_tutor_profile.break_promise_count),但此表保留全部历史
-- 关联:t_user(tutor)/ t_demand / t_order
-- ============================================================
CREATE TABLE t_break_promise_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 主键,自增
    tutor_user_id BIGINT    NOT NULL,                                  -- 反悔老师(关联 t_user.id)
    demand_id     BIGINT,                                              -- 关联需求(可空,关联 t_demand.id)
    order_id      BIGINT,                                              -- 关联订单(可空,关联 t_order.id)
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP         -- 反悔时间
);
CREATE INDEX idx_t_break_promise_tutor ON t_break_promise_log (tutor_user_id);  -- 按老师查询历史

COMMENT ON TABLE  t_break_promise_log            IS '反悔历史(仅后台;申诉恢复后计数清零,此表保留全部历史)';
COMMENT ON COLUMN t_break_promise_log.tutor_user_id IS '反悔老师(关联 t_user.id)';
COMMENT ON COLUMN t_break_promise_log.demand_id    IS '关联需求(可空)';
COMMENT ON COLUMN t_break_promise_log.order_id     IS '关联订单(可空)';
COMMENT ON COLUMN t_break_promise_log.created_at   IS '反悔时间';

-- ============================================================
-- 11. t_audit_log 审核日志表(仅后台)
-- 业务用途:客服全部人工审核动作的留痕,多客服可追溯
-- 关键规则:target_type 覆盖 tutor_cert/tutor_resume/parent_publish/evaluation/appeal/report/order
-- 关联:operator_id → system_users.id
-- ============================================================
CREATE TABLE t_audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 主键,自增
    target_type VARCHAR(16)  NOT NULL,                               -- 审核对象:tutor_cert / tutor_resume / parent_publish / evaluation / appeal / report / order
    target_id   BIGINT,                                              -- 目标 ID(对应对象表主键)
    action      SMALLINT     NOT NULL,                               -- 动作:1 通过 / 2 拒绝 / 3 隐藏 / 4 恢复 / 5 下线
    operator_id BIGINT,                                              -- 操作客服(关联 system_users.id,多客服可追溯)
    reason      VARCHAR(255),                                        -- 原因/备注
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP      -- 操作时间
);
CREATE INDEX idx_t_audit_log_target ON t_audit_log (target_type, target_id);  -- 按对象查询审核历史

COMMENT ON TABLE  t_audit_log              IS '人工审核动作留痕(仅后台,多客服可追溯)';
COMMENT ON COLUMN t_audit_log.target_type    IS '审核对象:tutor_cert / tutor_resume / parent_publish / evaluation / appeal / report / order';
COMMENT ON COLUMN t_audit_log.target_id      IS '目标 ID(对应对象表主键)';
COMMENT ON COLUMN t_audit_log.action         IS '动作:1 通过 / 2 拒绝 / 3 隐藏 / 4 恢复 / 5 下线';
COMMENT ON COLUMN t_audit_log.operator_id    IS '操作客服(关联 system_users.id)';
COMMENT ON COLUMN t_audit_log.reason         IS '原因/备注';
COMMENT ON COLUMN t_audit_log.created_at     IS '操作时间';

-- ============================================================
-- 完毕。字典种子数据迁移见 02-dict-data.sql(写入 yudao system_dict_data)
-- ============================================================
